security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        frontend_user_provider:
            entity:
                class: App\Entity\User
                property: userIdentifier
        api_user_provider:
            entity:
                class: App\Entity\ApiKey
        jwt:
            lexik_jwt:
                class: App\Security\JWTUser
        admin_user_provider:
            id: App\Security\Admin\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        frontend_token_refresh:
            pattern: '%route-frontend-token-refresh%'
            stateless: true
            refresh_jwt:
                provider: frontend_user_provider
        api_token_create:
          pattern:  '%route-api-token-create%'
          stateless: true
          custom_authenticators:
            - App\Security\Api\CreateAuthenticator
          provider: api_user_provider
        api_token_verify:
            pattern: '%route-api-token-verify%'
            stateless: true
            jwt:
                authenticator: App\Security\Jwt\VerifyAuthenticator
            provider: jwt
        frontend_token_create:
            pattern:  '%route-frontend-token-create%'
            stateless: true
            jwt: ~
            json_login:
                check_path: '%route-frontend-token-create%'
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            provider: frontend_user_provider
        frontend_token_verify:
            pattern: '%route-frontend-token-verify%'
            stateless: true
            jwt:
                authenticator: App\Security\Jwt\VerifyAuthenticator
            provider: jwt
        apikey_list:
            pattern: '%route-apikey-list%'
            stateless: true
            jwt: ~
            provider: jwt
        apikey_get_default:
            pattern: '%route-apikey-get-default%'
            stateless: true
            jwt: ~
            provider: jwt
        user_create:
            pattern:  '%route-user-create%'
            stateless: true
            custom_authenticators:
                - App\Security\Admin\Authenticator
            provider: admin_user_provider
            entry_point: App\Security\Admin\AuthenticationEntryPoint
        refresh_token_revoke:
            pattern:  '%route-refresh-token-revoke%'
            stateless: true
            custom_authenticators:
                - App\Security\Admin\Authenticator
            provider: admin_user_provider
            entry_point: App\Security\Admin\AuthenticationEntryPoint
        main:
            lazy: true
            provider: frontend_user_provider

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: '%route-frontend-token-refresh%', roles: PUBLIC_ACCESS }
        - { path: '%route-frontend-token-create%', roles: PUBLIC_ACCESS }
        - { path: '%route-frontend-token-verify%', roles: !php/const App\Security\UserRoleInterface::ROLE_USER }
        - { path: '%route-apikey-list%', roles: !php/const App\Security\UserRoleInterface::ROLE_USER }
        - { path: '%route-apikey-get-default%', roles: !php/const App\Security\UserRoleInterface::ROLE_USER }
        - { path: '%route-user-create%', roles: !php/const App\Security\UserRoleInterface::ROLE_ADMIN }
        - { path: '%route-refresh-token-revoke%', roles: !php/const App\Security\UserRoleInterface::ROLE_ADMIN }
        - { path: '%route-api-token-create%', roles: PUBLIC_ACCESS }
        - { path: '%route-api-token-verify%', roles: !php/const App\Security\UserRoleInterface::ROLE_USER }
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
