security:
    # https://symfony.com/doc/current/security/experimental_authenticators.html
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#c-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        jwt:
            lexik_jwt:
                class: App\Security\JWTUser
        admin_user_provider:
            id: App\Security\Admin\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        token_create:
            pattern:  !php/const App\Controller\TokenController::ROUTE_CREATE
            stateless: true
            jwt: ~
            json_login:
                check_path: !php/const App\Controller\TokenController::ROUTE_CREATE
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            provider: app_user_provider
        token_verify:
            pattern: !php/const App\Controller\TokenController::ROUTE_VERIFY
            stateless: true
            anonymous: false
            jwt: ~
            provider: jwt
        admin:
            pattern:  !php/const App\Controller\AdminController::ROUTE_PREFIX
            stateless: true
            custom_authenticators:
                - App\Security\Admin\Authenticator
            provider: admin_user_provider
        main:
            lazy: true
            provider: app_user_provider

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: !php/const App\Controller\TokenController::ROUTE_CREATE, roles: PUBLIC_ACCESS }
        - { path: !php/const App\Controller\TokenController::ROUTE_VERIFY, roles: !php/const App\Security\UserRoleInterface::ROLE_USER }
        - { path: !php/const App\Controller\AdminController::ROUTE_PREFIX, roles: !php/const App\Security\UserRoleInterface::ROLE_ADMIN }
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
