gesdinet_jwt_refresh_token:
  path: '%route-frontend-token-refresh%'

frontend_token_create:
  path: '%route-frontend-token-create%'

frontend_token_verify:
  path: '%route-frontend-token-verify%'

api_token_create:
  path: '%route-api-token-create%'

api_token_verify:
  path: '%route-api-token-verify%'
