api_login:
  path: /api/login
  methods: [POST]

api_refresh_token:
  path: /api/token/refresh
  methods: [POST]

custom_refresh_token:
  path: /custom/token/refresh
  methods: [POST]

gesdinet_jwt_refresh_token:
  path: '%route-frontend-token-refresh%'

frontend_token_create:
  path: '%route-frontend-token-create%'

frontend_token_verify:
  path: '%route-frontend-token-verify%'

api_token_create:
  path: '%route-api-token-create%'

api_token_verify:
  path: '%route-api-token-verify%'

admin_user_create:
  path: '%route-admin-user-create%'
  controller: App\Controller\AdminController::createUser
