frontend_token_create:
  path: '%route-frontend-token-create%'

frontend_token_verify:
  path: '%route-frontend-token-verify%'
  controller: App\Controller\FrontendTokenController::verify

api_token_create:
  path: '%route-api-token-create%'

api_token_verify:
  path: '%route-api-token-verify%'
  controller: App\Controller\ApiTokenController::verify
