frontend_token_refresh:
  path: '%route-frontend-token-refresh%'
  methods: [POST]

frontend_token_create:
  path: '%route-frontend-token-create%'
  methods: [POST]

frontend_token_verify:
  path: '%route-frontend-token-verify%'
  methods: [GET]

frontend_apikey_list:
  path: '%route-frontend-apikey-list%'
  methods: [GET]
  controller: App\Controller\ApiKeyController::list

api_token_create:
  path: '%route-api-token-create%'
  methods: [POST]

api_token_verify:
  path: '%route-api-token-verify%'
  methods: [GET]

admin_user_create:
  path: '%route-admin-user-create%'
  methods: [POST]
  controller: App\Controller\AdminController::createUser

admin_frontend_refreshtoken_revoke:
  path: '%route-admin-frontend-refresh-token-revoke%'
  methods: [POST]
  controller: App\Controller\AdminController::revokeRefreshToken

_health_check_bundle_routes:
  resource: '@HealthCheckBundle/Resources/config/routes.yaml'
