frontend_token_refresh:
  path: '%route-frontend-token-refresh%'
  methods: [POST]

frontend_token_create:
  path: '%route-frontend-token-create%'
  methods: [POST]

frontend_token_verify:
  path: '%route-frontend-token-verify%'

api_token_create:
  path: '%route-api-token-create%'

api_token_verify:
  path: '%route-api-token-verify%'

admin_user_create:
  path: '%route-admin-user-create%'
  controller: App\Controller\AdminController::createUser

admin_frontend_refreshtoken_revoke:
  path: '%route-admin-frontend-refresh-token-revoke%'
  methods: [POST]
  controller: App\Controller\AdminController::revokeRefreshToken

health_check:
  path: '%route-health-check%'
  methods: [GET]
  controller: App\Controller\HealthCheckController::get

status:
  path: '%route-status%'
  methods: [GET]
  controller: App\Controller\StatusController::get
