frontend_token_refresh:
  path: '%route-frontend-token-refresh%'
  methods: [POST]

frontend_token_create:
  path: '%route-frontend-token-create%'
  methods: [POST]

frontend_token_verify:
  path: '%route-frontend-token-verify%'
  methods: [GET]

apikey_list:
  path: '%route-apikey-list%'
  methods: [GET]
  controller: App\Controller\ApiKeyController::list

apikey_get_default:
  path: '%route-apikey-get-default%'
  methods: [GET]
  controller: App\Controller\ApiKeyController::getDefault

api_token_create:
  path: '%route-api-token-create%'
  methods: [POST]

api_token_verify:
  path: '%route-api-token-verify%'
  methods: [GET]

user_create:
  path: '%route-user-create%'
  methods: [POST]
  controller: App\Controller\UserController::create

refreshtoken_revoke:
  path: '%route-refresh-token-revoke-all-for-user%'
  methods: [POST]
  controller: App\Controller\RefreshTokenController::revoke

_health_check_bundle_routes:
  resource: '@HealthCheckBundle/Resources/config/routes.yaml'
