parameters:
    test_user_email: '%env(resolve:TEST_USER_EMAIL)%'
    test_user_password: '%env(TEST_USER_PASSWORD)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Services\UserFactory:
        public: true

    App\Tests\Services\UserRemover:
        public: true
