parameters:
    test_user_email: 'test-user-email'
    test_user_password: 'test-user-password'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Services\ApiKeyFactory:
        public: true

    App\Services\UserRefreshTokenManager:
        public: true

    App\Tests\Services\TestUserFactory:
        public: true
        arguments:
            $testUserEmail: '%test_user_email%'
            $testUserPassword: '%test_user_password%'

    App\Tests\Services\UserRemover:
        public: true

    App\Tests\Services\RefreshTokenManager:
        public: true

    app.tests.integration.http.client:
        public: true
        class: GuzzleHttp\Client
        arguments:
            $config:
                base_uri: "https://localhost/"
                verify: false

    Psr\Http\Client\ClientInterface:
        alias: app.tests.integration.http.client

    GuzzleHttp\Psr7\HttpFactory:

    Psr\Http\Message\RequestFactoryInterface:
        alias: GuzzleHttp\Psr7\HttpFactory

    Psr\Http\Message\ResponseFactoryInterface:
        alias: GuzzleHttp\Psr7\HttpFactory

    Psr\Http\Message\ServerRequestFactoryInterface:
        alias: GuzzleHttp\Psr7\HttpFactory

    Psr\Http\Message\StreamFactoryInterface:
        alias: GuzzleHttp\Psr7\HttpFactory

    Psr\Http\Message\UploadedFileFactoryInterface:
        alias: GuzzleHttp\Psr7\HttpFactory

    Psr\Http\Message\UriFactoryInterface:
        alias: GuzzleHttp\Psr7\HttpFactory

    Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface:
        class: Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory

    App\Tests\Services\ApplicationClient\ClientFactory:
        public: true

    SmartAssert\SymfonyTestClient\SymfonyClient:
        public: true

    SmartAssert\SymfonyTestClient\HttpClient:
        public: true
        arguments:
            $httpClient: '@app.tests.integration.http.client'
