name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit:
    name: Unit tests - PHP ${{ matrix.php }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php: ['8.0']
    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Run PHPUnit unit tests
        run: composer test-unit

  functional:
    name: Functional tests - PHP ${{ matrix.php }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php: ['8.0']
    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Setup functional test environment
        run: composer functional-setup

      - name: Run tests
        run: composer test-functional
        env:
          DATABASE_URL: postgres://postgres:password!@127.0.0.1:5432/users-db?charset=UTF-8
